dist: trusty
sudo: required
language: go
go:
  - "1.8"
  - "1.10.x"
services:
  - docker
install:
  - rm -rf vendor
before_script:
  - docker --version
  - docker-compose --version
  - sudo make test-full-prepare
script:
  - make test-full
