dist: trusty
sudo: required
language: go
go:
  - 1.10.x
  - master
matrix:
  allow_failures:
    - go: master
env:
  - MONGODB_DOCKERTAG=percona/percona-server-mongodb:3.4
  - MONGODB_DOCKERTAG=percona/percona-server-mongodb:3.6
  - MONGODB_DOCKERTAG=mongo:4.0
services:
  - docker
install:
  - make vendor
before_script:
  - docker --version
  - docker-compose --version
  - sudo make test-full-keys
  - make TEST_MONGODB_DOCKERTAG=$MONGODB_DOCKERTAG test-full-prepare
script:
  - make TEST_CODECOV=true test-full
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_script:
  - make test-full-clean
