dist: trusty
sudo: required
language: go
go:
  - 1.10.x
  - master
matrix:
  allow_failures:
    - go: master
env:
  - TEST_PSMDB_VERSION=3.4
  - TEST_PSMDB_VERSION=3.6
services:
  - docker
before_script:
  - docker --version
  - docker-compose --version
  - sudo make test-mongod.key
  - make TEST_PSMDB_VERSION=${TEST_PSMDB_VERSION} test-full-prepare
script:
  - make TEST_CODECOV=true test-full
after_success:
  - bash <(curl -s https://codecov.io/bash)
