dist: trusty
sudo: required
language: go
go:
  - 1.10.x
  - master
matrix:
  allow_failures:
    - go: master
services:
  - docker
install:
  - rm -rf vendor
before_script:
  - docker --version
  - docker-compose --version
  - sudo make test-mongod.key
  - make test-full-prepare
script:
  - make test-full
after_success:
  - bash <(curl -s https://codecov.io/bash)
